# 应用名称
server:
  port: 80

spring:
  datasource:
    druid:
      name: defaultDataSource
      url: jdbc:mysql://localhost:3306/jdbc?serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 1234%^&*gd
  devtools:
    restart:
      # 设置不参与热部署的文件或文件夹
      exclude: static/**,public/**
      enabled: true


mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb1_ # 对应数据库表增加字段
      id-type: auto  # 配置id自增策略
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
