# 应用名称
server:
  port: 80

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/test
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: 123456

#
#spring:
#  datasource:
##    druid:
#    name: defaultDataSource
#    url: jdbc:mysql://localhost:3306/jdbc?serverTimezone=UTC
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 1234%^&*gd
#  devtools:
#    restart:
#      # 设置不参与热部署的文件或文件夹
#      exclude: static/**,public/**
#      enabled: true
#  jdbc:
#    template:
#      fetch-size: 50
#      query-timeout: 3000
#
#
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_ # 对应数据库表增加字段
      id-type: auto  # 配置id自增策略
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


