# 应用名称
spring:
  application:
    name: springboot_03_mybits
  datasource:
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/jdbc?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234%^&*gd


  redis:
    port: 6379
    host: 127.0.0.1

#下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis:
#  mapper-locations: classpath:mappers/*xml
##指定Mybatis的实体目录
#  type-aliases-package: com.toec.springboot_03_mybits.mybatis.entity



